global using MonkeyCache;
global using MAUIApp.Framework.Exceptions;
global using MAUIApp.Framework.Extensions;
global using System.Net.Http.Headers;
global using System.Text.Json;
global using System.Text;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using CommunityToolkit.Mvvm.ComponentModel;